// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.ProjectRenamifier
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS-ProjectRenamifier";
        public const string Name = "VS-ProjectRenamifier";
        public const string Description = @"Project Renamifier!";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Coding With Calvin";
        public const string Tags = "";
    }
}
