// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.ProjectRenamifier
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ProjectRenamifierString = "57c39070-ff59-4bf6-8be3-1f4305ff1ec4";
        public static Guid ProjectRenamifier = new Guid(ProjectRenamifierString);

        public const string CommandSetGuidString = "1577166d-7d58-4ef1-af82-520a8966ae67";
        public static Guid CommandSetGuid = new Guid(CommandSetGuidString);

        public const string IconGuidString = "6a050d5f-fb67-4d45-b6fc-f6f2612aa8ad";
        public static Guid IconGuid = new Guid(IconGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RenamifyProjectCommandId = 0x0100;
        public const int FolderIcon = 0x0001;
    }
}